### ISSUE TITLE
add typings to make code more readable 

### ISSUE THREAD

**Issue by HassanBahati** [DaphineKamusiime/Software-Construction#3]
the solid principles implementation would be optimized and refactored to have data types specified

**Comment by AshabaJasper** [comment]
## Issue Resolution Confirmation

This is to confirm that the **Solid Principles implementation** has been optimized and refactored with the necessary typings to enhance code readability and maintainability.

The following actions have been completed:

- [x] Code has been reviewed to ensure typings are consistently applied.
- [x] Each function and variable has been annotated with specific data types.
- [x] The code has passed all the type checking without any type-related errors.
- [x] All changes have been tested to confirm that functionality remains intact.

With these points checked off, I am closing this issue as the objectives have been met.

---

Issue: `#3`  
Pull Request: `#5`  
Reviewer: `@AshabaJasper`  

---

Thank you for your contribution to maintaining the code quality of this project!
